### ISSUE TITLE
Battery perturbation adapts again after replanning.

### ISSUE THREAD

**Issue by schmerl** [cmu-mars/issues#99] opened 2018-05-18 18:21 UTC
**Description**: This was a C test case with c1c running
**Issue**: The planner replans once, starts executing the new plan, but then the battery evaluator determines the plan has not enough energy, and replans again.
**Start conditions**: c1c
**Steps to reproduce**:
```
curl -X POST "http://0.0.0.0:8080/start" -H "accept: application/json
curl -X POST "http://0.0.0.0:8080/perturb/battery" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"charge\": 3121.73}"
```
**Observations**:

1. Rainbow generates the new plan: `P(V(1, do SetCP1Config(7) then 2),V(2, do MoveAbsH(-21.08, 11.08, 0.98, -1.5708) then 3)::V(3, do MoveAbsH(-21.08, 0.00, 0.98, -1.5476) then 4)::V(4, do MoveAbsH(-20.81, -11.62, 0.98, -0.0123) then 5)::V(5, do MoveAbsH(1.08, -11.89, 0.98, 0.0000) then 6)::V(6, do MoveAbsH(23.24, -11.89, 0.98, 1.5708) then 7)::V(7, do MoveAbsH(23.24, -0.54, 0.98, 1.5946) then 8)::V(8, do MoveAbsH(22.97, 10.81, 0.98, 1.5946) then 9)::V(9, end)::nil)` in response to the perturbation. 
2. It executes one the first instruction (I think) and then:
```
INFO  Analyzer - BRASS Accuracy Evaluator: Do not have enough battery.
INFO  ESEBMasterReportingPort - ANALYSIS: BRASS Accuracy Evaluator: Do not have enough
 battery.
INFO  ESEBMasterReportingPort - 
INFO  Analyzer - BRASS Accuracy Evaluator: Inserting node 'l14' at (-21.1264335122, 0.
146379758523) between l10 and l7
INFO  ESEBMasterReportingPort - ANALYSIS: BRASS Accuracy Evaluator: Inserting node 'l1
4' at (-21.1264335122, 0.146379758523) between l10 and l7
INFO  ESEBMasterReportingPort - MODEL: Executing O[RainbowState:RainbowState/setModelP
roblem.([LOW_ON_BATTERY])]
INFO  ESEBMasterReportingPort - 
```

3. This causes the planner to issue another plan: `"P(V(1, do SetCP1Config(7) then 2),V(2, do MoveAbsH(-20.81, -11.62, 0.98, -0.0123) then 3)::V(3, do MoveAbsH(1.08, -11.89, 0.98, 0.0000) then 4)::V(4, do MoveAbsH(23.24, -11.89, 0.98, 1.5708) then 5)::V(5, do MoveAbsH(23.24, -0.54, 0.98, 1.5946) then 6)::V(6, do MoveAbsH(22.97, 10.81, 0.98, 1.5946) then 7)::V(7, end)::nil)"`

There seems to be some discrepancy between the planner and the simulator here (and maybe the power model learned and implemented). This could be either:

1. Planner doesn't have the right power model
2. The robot can't move as quickly as 0.98

[battery-perturbation-console.log](https://github.com/cmu-mars/issues/files/2018171/battery-perturbation-console.log)
[battery-perturbation-rainbow.log](https://github.com/cmu-mars/issues/files/2018172/battery-perturbation-rainbow.log)

**Comment by schmerl** [comment] 2018-05-18 18:30
Personally, I think the first thing to do is to establish the upper speed that the robot actually goes in gazebo. IIRC, I think that you can set a high speed but the robot doesn't necessarily go that speed. So that would throw off the planner.

**Comment by pooyanjamshidi** [comment] 2018-05-18 23:36
For our note, I made some changes in the backend to consider `0.68` as an upper limit for `speed`, so for our planner debugging, we exclude this option.

**Comment by schmerl** [comment] 2018-06-12 19:49
@pooyanjamshidi I assume that your change fixes the problem?

**Comment by pooyanjamshidi** [comment] 2018-06-18 16:47
@schmerl yes,I fixed the speed issue, but replanning might be OK, because the planner may reconfigure but still may need to go to a charging due to low battery, @javier-camara right?

**Comment by pooyanjamshidi** [comment] 2018-07-07 02:18
I'm closing this because the issue is resolved, but @javier-camara please provide an answer if relevant?

**Closed as completed by pooyanjamshidi** 2018-07-07 02:18 UTC
Labels: CP1
